# Generated by Django 3.2 on 2024-10-25 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text=' **El nombre no puede incluir espacios**', max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(regex='^[a-zA-Z]+$')])),
                ('apellido', models.CharField(help_text=' **El apellido no puede incluir espacios**', max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.RegexValidator(regex='^[a-zA-Z]+$')])),
                ('rut', models.CharField(help_text=" (ej.'12345678-9')", max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\d{7,8}-[\\dkK]$')])),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(5)])),
                ('telefono', models.CharField(default='000000000', help_text=" (ej.'912345678').", max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\d{9}$')])),
            ],
        ),
    ]
