# Generated by Django 3.2 on 2024-10-26 00:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='000000000', help_text=" (ej.'912345678').", max_length=9, validators=[django.core.validators.RegexValidator(regex='^\\d{9}$')]),
        ),
    ]
