# Generated by Django 3.2 on 2024-10-26 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clienteApp', '0003_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(help_text=" (ej.'912345678').", max_length=9),
        ),
    ]
